package service

// ParamDef 单个参数定义（用于 Seed 初始化）
type ParamDef struct {
	Group        string
	Key          string
	Name         string
	Description  string
	ValueType    string
	DefaultValue string
	Min          *string
	Max          *string
	Step         *string
	ReadOnly     bool
	Restart      bool
	Category     string
}

func strPtr(s string) *string { return &s }

// DefaultParamDefs 返回全部默认参数定义
//
// 来源：项目内 ~60 处硬编码 const（bridge/handler_http.go、
// knowledge/service/constants.go、smart_cs_orchestrator.go、
// customer_session.go、cache/memory.go 等）。
//
// 设计原则：
//  1. 每一条对应一个现存的硬编码 const
//  2. Group 按业务域划分：bridge / knowledge / agent_llm / smart_cs /
//     session / cache / pagination / wecom / telemetry / sales / misc
//  3. Min/Max/Step 基于参数语义的合理范围（用于 UI slider/number input）
//
// 「登记」不等于「接通」：本清单会被参数中心整份渲染成可编辑控件，而只有被生产代码
// 读走的那些改了才真生效。没读取点的条目一律在 Name 上挂「（未接线）」、Description 上挂
// 「【当前不生效，改了也没人读】」，让页面自己说清这条能不能用；将来把它接线之后，
// 必须把这两句撤掉，否则门会报 STALE。
// 判据与当前读数（有读取点／已声明未接线 各多少条）由 scripts/check-config-param-readpoints.py
// 现测打印，本注释不复述数字（复述的那个数在代码一改之后就会漂）。
func DefaultParamDefs() []ParamDef {
	return []ParamDef{

		{Group: "permission", Key: "role_permissions_json", Name: "角色权限矩阵",
			Description: "JSON: {角色码: [权限项]}；权限项支持 module.* 通配；admin 恒全权不走此配置",
			ValueType:   "string", DefaultValue: `{"customer_service":["cards.*","shortlinks.*","clues.*","autoreply.*"],"staff":["cards.view","shortlinks.view","clues.view"]}`, Category: "权限"},

		{Group: "reach", Key: "global_per_user_daily_limit", Name: "单客户全管线日触达上限",
			Description: "同一客户被全部触达管线共享的每日（CST 自然日）触达上限；0=禁用该层",
			ValueType:   "int", DefaultValue: "3", Min: strPtr("0"), Max: strPtr("50"), Category: "触达"},

		{Group: "bridge", Key: "polling_max_timeout", Name: "轮询最大超时（未接线）",
			Description: "【当前不生效，改了也没人读】服务端没有 HTTP 长轮询实现：ingest 立即返回，回复由扩展走 SSE 或 /outbox 轮询。internal/bridge/handler_http.go 的 HTTPPollingMaxTimeout 全树只有 defaults_test.go 引用。要启用请先实现长轮询分支，并把该常量改成本参数的读取口",
			ValueType:   "duration", DefaultValue: "500", Min: strPtr("10"), Max: strPtr("3600"), Step: strPtr("5")},
		{Group: "bridge", Key: "polling_default_timeout", Name: "轮询默认超时（未接线）",
			Description: "【当前改了下也不生效】同上，长轮询未实现。bridge/handler_http.go 的 HTTPPollingDefaultTimeout 全树只有 defaults_test.go 引用",
			ValueType:   "duration", DefaultValue: "30", Min: strPtr("5"), Max: strPtr("120"), Step: strPtr("1")},
		{Group: "bridge", Key: "ingest_max_body_bytes", Name: "Ingest 请求体上限",
			Description: "bridge/ingest 单次请求体最大字节数",
			ValueType:   "int", DefaultValue: "4194304", Min: strPtr("1048576"), Max: strPtr("67108864")},
		{Group: "bridge", Key: "ingest_max_messages", Name: "Ingest 单次消息数上限",
			Description: "单次上报最多携带的消息条数",
			ValueType:   "int", DefaultValue: "200", Min: strPtr("10"), Max: strPtr("2000"), Step: strPtr("10")},
		{Group: "bridge", Key: "sse_heartbeat_interval", Name: "SSE 心跳间隔",
			Description: "SSE 空闲时服务端向客户端发送心跳包的间隔（秒）",
			ValueType:   "duration", DefaultValue: "15", Min: strPtr("5"), Max: strPtr("60"), Step: strPtr("1")},
		{Group: "bridge", Key: "max_reply_content_bytes", Name: "回复内容截断上限（未接线）",
			Description: "【当前不生效，改了也没人读】internal/bridge/bridge_helpers.go 的 maxReplyContentBytes 标注了 nolint:unused——生产路径没有任何回复内容截断逻辑。要启用请在出网前对该字段做截断，并把它接到本参数",
			ValueType:   "int", DefaultValue: "4096", Min: strPtr("1024"), Max: strPtr("65536"), Step: strPtr("256")},
		{Group: "bridge", Key: "max_ack_msg_ids", Name: "ACK 单次消息ID数上限",
			Description: "客户端一次 ACK 最多携带的消息 ID 数",
			ValueType:   "int", DefaultValue: "500", Min: strPtr("50"), Max: strPtr("5000"), Step: strPtr("50")},
		{Group: "bridge", Key: "online_grace_window", Name: "在线状态宽限窗口",
			Description: "渠道账号心跳丢失后仍判定为在线的宽限时间（秒）",
			ValueType:   "duration", DefaultValue: "30", Min: strPtr("10"), Max: strPtr("300"), Step: strPtr("5")},
		{Group: "bridge", Key: "outbound_orphan_ttl", Name: "出站孤儿行结算阈值",
			Description: "桥接渠道出站消息在「账号未注册或已超过此时长未同步」时，行本身超过此时长即落 failed（原因 outbound_orphan_expired）；0 表示停用该结算",
			ValueType:   "duration", DefaultValue: "604800", Min: strPtr("0"), Max: strPtr("7776000"), Step: strPtr("3600")},
		{Group: "bridge", Key: "outbound_orphan_dry_run", Name: "出站孤儿行结算只报数",
			Description: "true（缺省）＝后台回扫只统计并打印候选行数，不写库；确认过报数后改 false 才真正把孤儿行落 failed。落 failed 不可逆（内容不动，但状态离开待办集合），所以开关默认停在报数一侧",
			ValueType:   "bool", DefaultValue: "true"},

		{Group: "knowledge", Key: "default_top_k", Name: "默认 Top-K 检索数",
			Description: "向量检索返回的候选文档数",
			ValueType:   "int", DefaultValue: "5", Min: strPtr("1"), Max: strPtr("50"), Step: strPtr("1")},
		{Group: "knowledge", Key: "similarity_threshold", Name: "相似度阈值",
			Description: "向量检索相似度低于此值视为无相关内容（0-1）",
			ValueType:   "float", DefaultValue: "0.5", Min: strPtr("0.1"), Max: strPtr("0.95"), Step: strPtr("0.05")},
		{Group: "knowledge", Key: "chunk_preview_max_len", Name: "分片内容预览长度",
			Description: "检索结果 Content 字段截断长度",
			ValueType:   "int", DefaultValue: "500", Min: strPtr("100"), Max: strPtr("5000"), Step: strPtr("50")},
		{Group: "knowledge", Key: "max_search_list_size", Name: "检索扫描上限",
			Description: "BM25-lite 兜底路径扫描的最大条目数",
			ValueType:   "int", DefaultValue: "1000", Min: strPtr("100"), Max: strPtr("100000"), Step: strPtr("100")},
		{Group: "knowledge", Key: "bm25_scan_limit", Name: "BM25 文本匹配上限",
			Description: "BM25 关键词匹配扫描的最大分片数",
			ValueType:   "int", DefaultValue: "10000", Min: strPtr("1000"), Max: strPtr("500000"), Step: strPtr("1000")},
		{Group: "knowledge", Key: "embedding_dimension", Name: "Embedding 维度",
			Description: "向量嵌入维度（bge-m3 默认 1024）",
			ValueType:   "int", DefaultValue: "1024", Min: strPtr("128"), Max: strPtr("8192"), ReadOnly: true},
		{Group: "knowledge", Key: "async_processing_timeout", Name: "异步处理超时",
			Description: "文档异步处理（分片+embedding+索引）总超时（秒）",
			ValueType:   "duration", DefaultValue: "900", Min: strPtr("60"), Max: strPtr("7200"), Step: strPtr("60")},
		{Group: "knowledge", Key: "external_import_timeout", Name: "外部导入超时",
			Description: "飞书/Notion 外部导入总超时（秒）",
			ValueType:   "duration", DefaultValue: "1800", Min: strPtr("60"), Max: strPtr("7200"), Step: strPtr("60")},
		{Group: "knowledge", Key: "ssrf_check_timeout", Name: "SSRF 防护超时",
			Description: "外部 URL SSRF 校验的单次 HTTP 超时（秒）",
			ValueType:   "duration", DefaultValue: "5", Min: strPtr("1"), Max: strPtr("60"), Step: strPtr("1")},
		{Group: "knowledge", Key: "embedding_max_batch", Name: "Embedding 最大批大小",
			Description: "单次 embedding 向量化调用的最大文本批数",
			ValueType:   "int", DefaultValue: "64", Min: strPtr("1"), Max: strPtr("1024"), Step: strPtr("8")},

		{Group: "agent_llm", Key: "temperature", Name: "LLM Temperature",
			Description: "采样温度，越大输出越发散（0-2）",
			ValueType:   "float", DefaultValue: "0.7", Min: strPtr("0.1"), Max: strPtr("2.0"), Step: strPtr("0.1")},
		{Group: "agent_llm", Key: "max_tokens", Name: "LLM Max Tokens",
			Description: "单次 LLM 调用最大生成 token 数",
			ValueType:   "int", DefaultValue: "1000", Min: strPtr("64"), Max: strPtr("8192"), Step: strPtr("64")},
		{Group: "agent_llm", Key: "top_p", Name: "LLM Top-P",
			Description: "核采样概率阈值（0-1）",
			ValueType:   "float", DefaultValue: "0.9", Min: strPtr("0.5"), Max: strPtr("1.0"), Step: strPtr("0.05")},
		{Group: "agent_llm", Key: "request_timeout", Name: "LLM 请求超时",
			Description: "单次 LLM HTTP 请求超时（秒）",
			ValueType:   "duration", DefaultValue: "60", Min: strPtr("5"), Max: strPtr("600"), Step: strPtr("5")},
		{Group: "agent_llm", Key: "max_retries", Name: "LLM 最大重试",
			Description: "LLM 调用失败后自动重试次数",
			ValueType:   "int", DefaultValue: "3", Min: strPtr("0"), Max: strPtr("10"), Step: strPtr("1")},
		{Group: "agent_llm", Key: "agent_loop_drift_factor", Name: "AgentLoop 漂移因子",
			Description: "智能体循环步数相对阈值的放宽倍数（超过阈值×factor 触发降级）",
			ValueType:   "float", DefaultValue: "2.5", Min: strPtr("1.0"), Max: strPtr("10.0"), Step: strPtr("0.1")},
		{Group: "agent_llm", Key: "minor_llm_threshold", Name: "轻量 LLM 意图阈值",
			Description: "意图识别置信度低于此值时只调用轻量模型（非完整 LLM）",
			ValueType:   "float", DefaultValue: "0.6", Min: strPtr("0.3"), Max: strPtr("0.95"), Step: strPtr("0.05")},
		{Group: "agent_llm", Key: "geo_max_tokens_per_call", Name: "Geo LLM 单调 Token 上限",
			Description: "内容分析 Geo 场景单次 LLM 调用的最大 token",
			ValueType:   "int", DefaultValue: "4000", Min: strPtr("512"), Max: strPtr("32768"), Step: strPtr("256")},

		{Group: "smart_cs", Key: "confidence_threshold", Name: "智能客服置信度阈值",
			Description: "置信度高于此值才走自动 AI 回复，否则转人工",
			ValueType:   "float", DefaultValue: "0.7", Min: strPtr("0.3"), Max: strPtr("0.99"), Step: strPtr("0.05")},
		{Group: "smart_cs", Key: "enable_auto_reply", Name: "开启自动回复",
			Description: "是否允许智能体自动回复（false 时全部转人工）",
			ValueType:   "bool", DefaultValue: "true"},
		{Group: "smart_cs", Key: "max_ai_consecutive", Name: "AI 连续回复上限",
			Description: "同一会话内 AI 连续回复超过此次数后强制转人工",
			ValueType:   "int", DefaultValue: "10", Min: strPtr("2"), Max: strPtr("50"), Step: strPtr("1")},

		// human_task.handoff_first_response_minutes（T-P3-03）：键名这里是一串字面量、
		// 服务侧读的是 service.HumanTaskConfigGroup / HumanTaskHandoffSlaKey 两个常量，
		// 两边打错任意一处都**不会报错**，只会让运维改参数永远不生效（GetInt 安静回退默认值）。
		// 所以一致性由 TestHumanTaskSeedKeyMatchesServiceConstants 逐字锁住。
		{Group: "human_task", Key: "handoff_first_response_minutes", Name: "转人工首响时限（分钟）",
			Description: "会话转人工后坐席首次响应的时限，超时即计入人工待办逾期读数；1~1440 之外一律回退默认 5 分钟",
			ValueType:   "int", DefaultValue: "5", Min: strPtr("1"), Max: strPtr("1440"), Step: strPtr("1")},

		{Group: "session", Key: "active_ttl", Name: "会话活跃 TTL",
			Description: "无任何消息交互超过此时间后会话自动关闭（秒）",
			ValueType:   "duration", DefaultValue: "86400", Min: strPtr("300"), Max: strPtr("2592000"), Step: strPtr("3600")},
		{Group: "session", Key: "idle_ttl", Name: "MCP 会话空闲 TTL",
			Description: "MCP Server 会话无活动超过此时间后过期（秒）",
			ValueType:   "duration", DefaultValue: "1800", Min: strPtr("60"), Max: strPtr("86400"), Step: strPtr("60")},
		{Group: "session", Key: "max_delay_seconds", Name: "营销流程 delay 节点等待上限（秒）",
			Description: "营销流程 delay 节点单次等待时长的上限（秒），超过则截断（不是放弃）。注意这条不是触达排程的「超期放弃」——代码里没有那个概念",
			ValueType:   "duration", DefaultValue: "300", Min: strPtr("30"), Max: strPtr("3600"), Step: strPtr("10")},

		{Group: "cache", Key: "max_keys", Name: "内存缓存最大键数",
			Description: "进程内内存缓存的最大条目数（超过会触发 LRU 淘汰）",
			ValueType:   "int", DefaultValue: "10000", Min: strPtr("1000"), Max: strPtr("1000000"), Step: strPtr("1000")},
		{Group: "cache", Key: "faq_answer_enabled", Name: "开启 FAQ 语义答案缓存",
			Description: "默认关。打开后编排器每次入会话先做一次 embedding 并查 rag_answer_cache，命中即直接回缓存答案、跳过本轮生成（代价：多一次向化调用，以及相近问题会复用同一条答案）；装配点在 app/faq_cache_wiring.go。生效范围还受下面两格约束",
			ValueType:   "bool", DefaultValue: "false"},
		{Group: "cache", Key: "faq_ttl", Name: "FAQ 答案缓存 TTL",
			Description: "缓存条目最长可用时间（秒）：命中校验时条目已超龄就删掉该行并按未命中处理。只在 cache.faq_answer_enabled 为真时有人读（app/faq_cache_wiring.go）",
			ValueType:   "duration", DefaultValue: "300", Min: strPtr("60"), Max: strPtr("86400"), Step: strPtr("60")},
		{Group: "cache", Key: "faq_decay_max_batch", Name: "FAQ 衰减批量",
			Description: "后台 FAQ 分数衰减任务每轮处理的最大条目",
			ValueType:   "int", DefaultValue: "1000", Min: strPtr("100"), Max: strPtr("100000"), Step: strPtr("100")},

		{Group: "pagination", Key: "page_max_size", Name: "单页最大条数（未接线）",
			Description: "【当前不生效，改了也没人读】internal/pkg/utils/pagination.go 的 defaultMaxPageSize=200 只被 newDefaultConfig() 用，而 newDefaultConfig 只被 ParsePagination/ParsePaginationOffset 用——这两个函数全树只有 pagination_test.go 调用，零生产调用方。另注：种子写 100，代码写 200，两者本就不一致",
			ValueType:   "int", DefaultValue: "100", Min: strPtr("10"), Max: strPtr("10000"), Step: strPtr("10")},
		{Group: "pagination", Key: "page_default_size", Name: "默认分页大小（未接线）",
			Description: "【当前不生效，改了也没人读】internal/pkg/utils/pagination.go 的 defaultDefaultPageSize 有两处消费：一处是上面那条不可达的 newDefaultConfig，另一处是 ParseCursorParams 的 limit 未指定兜底分支——但 operation_log / security_audit / customer 三个调用方都传了正数 defaultLimit，把那条分支遮蔽了",
			ValueType:   "int", DefaultValue: "20", Min: strPtr("5"), Max: strPtr("500"), Step: strPtr("5")},
		{Group: "pagination", Key: "cursor_page_size", Name: "游标分页大小",
			Description: "游标分页（Cursor）每批拉取的数量",
			ValueType:   "int", DefaultValue: "100", Min: strPtr("10"), Max: strPtr("1000"), Step: strPtr("10")},

		{Group: "wecom", Key: "error_rate_degrade", Name: "错误率降级阈值（未接线）",
			Description: "【当前不生效，改了也没人读】现存 computeHealthScore 的成功率判定是写死的三档（<50 扣 30 / <80 扣 15 / <95 扣 5），单一「错误率阈值」表达不了这种递减分档；硬套进来只能新造第四档或改掉现有扣分行为，所以没接。要真做成可配，需要先定「单一阈值 + 固定扣分」还是「保留三档只让档位可配」",
			ValueType:   "float", DefaultValue: "0.3", Min: strPtr("0.05"), Max: strPtr("0.95"), Step: strPtr("0.05")},
		{Group: "wecom", Key: "quota_degrade", Name: "配额降级阈值",
			Description: "企微消息使用率超过此比例触发限流（0-1）",
			ValueType:   "float", DefaultValue: "0.9", Min: strPtr("0.5"), Max: strPtr("1.0"), Step: strPtr("0.05")},

		{Group: "telemetry", Key: "node_health_window", Name: "节点健康检查窗口",
			Description: "节点健康心跳统计窗口（秒）。0 会让聚合恒为空列表，界面像是所有渠道都没心跳。",
			ValueType:   "duration", DefaultValue: "86400", Min: strPtr("3600"), Max: strPtr("604800"), Step: strPtr("3600")},
		{Group: "telemetry", Key: "trace_sink_buffer", Name: "Trace Sink 缓冲",
			Description: "追踪采集缓冲队列容量（超过丢弃低优先级事件）",
			ValueType:   "int", DefaultValue: "2048", Min: strPtr("256"), Max: strPtr("524288"), Step: strPtr("256")},
		{Group: "telemetry", Key: "geo_position_window", Name: "品牌词命中去重窗口",
			Description: "Geo 品牌词提及量统计时，相邻两处命中的字符间隔小于该值即算同一处提及（如「Apple 发布会」只计一次）。单位是字符偏移，不是条数。",
			ValueType:   "int", DefaultValue: "20", Min: strPtr("5"), Max: strPtr("100"), Step: strPtr("1")},
		{Group: "telemetry", Key: "feature_flag_poll_interval", Name: "Feature Flag 轮询间隔",
			Description: "pkg/featureflag 从环境变量热加载开关的轮询周期（秒）。改小会让每次轮询都读一遍环境变量；配 0 会被回落成代码兜底值，因为 time.NewTicker(0) 直接 panic。",
			ValueType:   "duration", DefaultValue: "5", Min: strPtr("1"), Max: strPtr("300"), Step: strPtr("1")},

		{Group: "sales", Key: "insight_limit", Name: "销售洞察条数（未接线）",
			Description: "【当前不生效，改了也没人读】trace_learning.TopInsights 的 limit 是入参不是默认值，全仓唯一调用方是 insights_test.go，生产链路没有任何地方取这个数量；要接得先有一个生产调用方把 limit 传进来",
			ValueType:   "int", DefaultValue: "3", Min: strPtr("1"), Max: strPtr("20"), Step: strPtr("1")},
		{Group: "sales", Key: "identity_max_attempts", Name: "客户身份合并重试上限",
			Description: "CustomerIdentity 身份合并的最大重试次数",
			ValueType:   "int", DefaultValue: "8", Min: strPtr("1"), Max: strPtr("50"), Step: strPtr("1")},

		{Group: "misc", Key: "upload_max_size_mb", Name: "上传文件大小上限",
			Description: "单次上传的文件大小上限（MB）。0 表示不覆盖、沿用下游：优先级为 env UPLOAD_MAX_SIZE > 本参数 > 「系统配置」页的兼容列 > 代码兜底 10MB。默认 0 是为了让存量站点保持现状——填 10 会把运维已在系统配置页调好的 200MB 又压回 10MB",
			ValueType:   "int", DefaultValue: "0", Min: strPtr("0"), Max: strPtr("512"), Step: strPtr("1")},
		{Group: "misc", Key: "visitor_token_ttl", Name: "访客 Token TTL",
			Description: "未登录访客的身份 Token 有效期（秒）",
			ValueType:   "duration", DefaultValue: "604800", Min: strPtr("3600"), Max: strPtr("2592000"), Step: strPtr("3600")},
		{Group: "misc", Key: "sso_cookie_ttl", Name: "SSO Cookie TTL",
			Description: "SSO 单点登录 cookie 的有效期（秒）",
			ValueType:   "duration", DefaultValue: "300", Min: strPtr("60"), Max: strPtr("86400"), Step: strPtr("60")},
		{Group: "misc", Key: "heartbeat_interval", Name: "平台心跳间隔",
			Description: "向平台发送心跳的周期（秒）",
			ValueType:   "duration", DefaultValue: "180", Min: strPtr("30"), Max: strPtr("3600"), Step: strPtr("10")},
		{Group: "misc", Key: "polling_lock_stale_threshold", Name: "轮询锁过期阈值",
			Description: "Telegram 等渠道 polling lock 超过此时间未更新视为失效（秒）",
			ValueType:   "duration", DefaultValue: "60", Min: strPtr("10"), Max: strPtr("600"), Step: strPtr("5")},
		{Group: "misc", Key: "domain_check_concurrency", Name: "域名检测并发",
			Description: "域名可用性检查的并发 goroutine 数",
			ValueType:   "int", DefaultValue: "16", Min: strPtr("1"), Max: strPtr("128"), Step: strPtr("1")},
		{Group: "misc", Key: "ab_exposure_buffer", Name: "AB 曝光缓冲",
			Description: "AB 实验曝光事件的批量缓冲大小",
			ValueType:   "int", DefaultValue: "1024", Min: strPtr("64"), Max: strPtr("65536"), Step: strPtr("64")},
		{Group: "misc", Key: "sms_max_retry", Name: "短信最大重试次数",
			Description: "短信发送失败后的重试次数",
			ValueType:   "int", DefaultValue: "3", Min: strPtr("0"), Max: strPtr("10"), Step: strPtr("1")},
		{Group: "misc", Key: "csv_export_max_rows", Name: "CSV 导出最大行数",
			Description: "自定义报表 CSV 导出的单行上限（防止 OOM）",
			ValueType:   "int", DefaultValue: "30000", Min: strPtr("1000"), Max: strPtr("500000"), Step: strPtr("1000")},
		{Group: "misc", Key: "backup_page_size", Name: "备份列表单页上限",
			Description: "备份列表单页最多返回多少条（超出按此截断）。注意这是上限不是默认分页大小：默认每页仍是 10 条，由 controller/backup.go 的 defaultBackupPageSize 决定",
			ValueType:   "int", DefaultValue: "1000", Min: strPtr("100"), Max: strPtr("100000"), Step: strPtr("100")},
		{Group: "misc", Key: "text_truncate_max_bytes", Name: "文本截断上限",
			Description: "文本工具通用截断的最大字节数",
			ValueType:   "int", DefaultValue: "8192", Min: strPtr("512"), Max: strPtr("1048576"), Step: strPtr("256")},
		{Group: "misc", Key: "preview_max_len", Name: "消息预览最大长度",
			Description: "消息列表 preview 字段的最大字符长度",
			ValueType:   "int", DefaultValue: "500", Min: strPtr("50"), Max: strPtr("5000"), Step: strPtr("50")},
		{Group: "misc", Key: "sop_scheduler_interval", Name: "SOP Scheduler 扫描间隔",
			Description: "SOP 调度器扫描待触发任务的周期（秒）",
			ValueType:   "duration", DefaultValue: "60", Min: strPtr("5"), Max: strPtr("600"), Step: strPtr("5")},
		{Group: "misc", Key: "sop_max_wait", Name: "SOP Timer 最大等待",
			Description: "SOP 定时器的最大等待时间（超过视为异常）",
			ValueType:   "duration", DefaultValue: "86400", Min: strPtr("3600"), Max: strPtr("2592000"), Step: strPtr("3600")},

		{Group: "channelgw", Key: "ws_register_timeout", Name: "WS 注册超时",
			Description: "Channel Gateway WebSocket 注册握手超时（秒）",
			ValueType:   "duration", DefaultValue: "15", Min: strPtr("5"), Max: strPtr("60"), Step: strPtr("1")},
		{Group: "channelgw", Key: "ws_read_idle_timeout", Name: "WS 读空闲超时",
			Description: "WebSocket 读取空闲超时（秒），超过触发重连",
			ValueType:   "duration", DefaultValue: "90", Min: strPtr("10"), Max: strPtr("600"), Step: strPtr("5")},
		{Group: "channelgw", Key: "ws_write_timeout", Name: "WS 写超时",
			Description: "WebSocket 单次写超时（秒）",
			ValueType:   "duration", DefaultValue: "10", Min: strPtr("1"), Max: strPtr("60"), Step: strPtr("1")},
		{Group: "channelgw", Key: "ws_push_interval", Name: "WS 推送间隔",
			Description: "心跳空闲时 WS 推送消息的最小间隔（秒）",
			ValueType:   "duration", DefaultValue: "2", Min: strPtr("1"), Max: strPtr("10"), Step: strPtr("1")},
		{Group: "channelgw", Key: "ws_pipeline_timeout", Name: "WS Pipeline 超时",
			Description: "WS pipeline 单次批量处理超时（秒）",
			ValueType:   "duration", DefaultValue: "30", Min: strPtr("5"), Max: strPtr("300"), Step: strPtr("5")},

		{Group: "agent_tool", Key: "max_concurrent", Name: "工具最大并发",
			Description: "Agent 工具执行器同时运行的最大并发数",
			ValueType:   "int", DefaultValue: "5", Min: strPtr("1"), Max: strPtr("50"), Step: strPtr("1")},
		{Group: "agent_tool", Key: "max_content_len", Name: "工具输出截断上限",
			Description: "工具返回内容超过此长度时截断",
			ValueType:   "int", DefaultValue: "4000", Min: strPtr("512"), Max: strPtr("65536"), Step: strPtr("256")},
		{Group: "agent_tool", Key: "result_cache_ttl", Name: "工具结果缓存 TTL（未接线）",
			Description: "【当前不生效，改了也没人读】ResultCache 的实现在 tooluse/result_cache.go，但 NewResultCache 全仓只有测试调用，生产链路从未构造过它——没有构造点就接不上 TTL。要启用需先在 executor 装饰链上挂 ResultCache，再把本条接进去",
			ValueType:   "duration", DefaultValue: "60", Min: strPtr("10"), Max: strPtr("3600"), Step: strPtr("5")},
		{Group: "agent_tool", Key: "cooldown_duration", Name: "工具冷却时间",
			Description: "工具失败后自动冷却时间（秒）",
			ValueType:   "duration", DefaultValue: "30", Min: strPtr("5"), Max: strPtr("300"), Step: strPtr("5")},
		{Group: "agent_tool", Key: "fail_threshold", Name: "工具熔断阈值",
			Description: "连续失败多少次后触发熔断",
			ValueType:   "int", DefaultValue: "5", Min: strPtr("1"), Max: strPtr("50"), Step: strPtr("1")},

		{Group: "middleware", Key: "audit_flush_interval", Name: "审计刷盘间隔",
			Description: "审计中间件批量刷盘到 DB 的时间间隔（秒）",
			ValueType:   "duration", DefaultValue: "5", Min: strPtr("1"), Max: strPtr("300"), Step: strPtr("1")},
		{Group: "middleware", Key: "mfa_recent_verify_ttl", Name: "MFA 近验有效期",
			Description: "MFA 二次验证后的宽限期（秒）",
			ValueType:   "duration", DefaultValue: "300", Min: strPtr("60"), Max: strPtr("3600"), Step: strPtr("60")},
		{Group: "middleware", Key: "max_json_body_mb", Name: "全局请求体上限",
			Description: "JSON / 表单请求体的全局封顶（MB）。必须高于各端点既有上界（webhook 可调顶格 4MB），调小会把已放行的高段请求截成半份；env MAX_JSON_BODY_MB 仍可覆盖。临时放开请用 env 设 0（不限制），本参数最小为 1。改动需重启",
			ValueType:   "int", DefaultValue: "8", Min: strPtr("1"), Max: strPtr("100"), Step: strPtr("1"), Restart: true},

		{Group: "confidence", Key: "humanize_default_threshold", Name: "人性化默认阈值",
			Description: "文本人性化判定阈值（0-1），落库到 humanize_scores.threshold；装配点 app/confidence_params_wiring.go",
			ValueType:   "float", DefaultValue: "0.85", Min: strPtr("0.1"), Max: strPtr("1.0"), Step: strPtr("0.05")},
		{Group: "confidence", Key: "persona_default_threshold", Name: "人设默认阈值（未接线）",
			Description: "【当前不生效，改了也没人读】人设匹配判定阈值（0-1）。对应实现 persona_evaluator.go 已随 9a5f716c 整体删除，当前代码里没有等价能力可接",
			ValueType:   "float", DefaultValue: "0.85", Min: strPtr("0.1"), Max: strPtr("1.0"), Step: strPtr("0.05")},
		{Group: "confidence", Key: "persona_max_retry", Name: "人设最大重试（未接线）",
			Description: "【当前不生效，改了也没人读】人设评估失败后最大重试次数。同上，实现已随 9a5f716c 删除；现存的重生成能力是 humanize（maxRetry），若要暴露请另立 humanize_max_retry 而不是改这条",
			ValueType:   "int", DefaultValue: "3", Min: strPtr("0"), Max: strPtr("10"), Step: strPtr("1")},
		{Group: "confidence", Key: "intent_fewshot_min_cos", Name: "意图 Few-Shot 最小余弦",
			Description: "意图识别 Few-Shot 检索最小余弦相似度（0-1），低于它的样本不进 prompt；装配点 app/confidence_params_wiring.go",
			ValueType:   "float", DefaultValue: "0.7", Min: strPtr("0.1"), Max: strPtr("1.0"), Step: strPtr("0.05")},
		{Group: "confidence", Key: "weak_truth_min_confidence", Name: "弱真值最小置信度",
			Description: "意图指标弱真值判定的最小置信度（0-1），低于它的预测进低置信桶、不入混淆矩阵；装配点 app/confidence_params_wiring.go",
			ValueType:   "float", DefaultValue: "0.9", Min: strPtr("0.1"), Max: strPtr("1.0"), Step: strPtr("0.05")},
		{Group: "confidence", Key: "emb_retry_cooldown", Name: "Embedding 重试冷却",
			Description: "Embedding 锚点预计算失败后的重试冷却间隔（秒），冷却期内不重复触发后台重算；装配点 app/confidence_params_wiring.go",
			ValueType:   "duration", DefaultValue: "60", Min: strPtr("5"), Max: strPtr("300"), Step: strPtr("5")},
		{Group: "confidence", Key: "veto_low_rag_threshold", Name: "否决低 RAG 阈值",
			Description: "一票否决规则的最低 RAG 得分阈值（0-1），RAGQual 低于它判定知识库无覆盖、必须转人工或兜底；装配点 app/confidence_params_wiring.go",
			ValueType:   "float", DefaultValue: "0.1", Min: strPtr("0"), Max: strPtr("0.5"), Step: strPtr("0.01")},

		{Group: "workflow", Key: "max_subflow_depth", Name: "子流程最大深度",
			Description: "子流程嵌套最大层级，防止无限递归",
			ValueType:   "int", DefaultValue: "5", Min: strPtr("1"), Max: strPtr("30"), Step: strPtr("1")},
		{Group: "workflow", Key: "max_workflow_steps", Name: "工作流最大步数",
			Description: "单个工作流最多可执行的节点数",
			ValueType:   "int", DefaultValue: "1000", Min: strPtr("10"), Max: strPtr("100000"), Step: strPtr("10")},
		{Group: "workflow", Key: "max_running_per_sop", Name: "单 SOP 最大并发",
			Description: "同一个 SOP 模板同时运行的最大实例数",
			ValueType:   "int", DefaultValue: "50", Min: strPtr("1"), Max: strPtr("500"), Step: strPtr("1")},
		{Group: "workflow", Key: "max_executed_node_trace", Name: "执行轨迹最大节点",
			Description: "SOP 执行历史记录最多保留的节点数",
			ValueType:   "int", DefaultValue: "200", Min: strPtr("10"), Max: strPtr("10000"), Step: strPtr("10")},

		{Group: "session", Key: "inbox_overdue_threshold", Name: "收件箱超时阈值",
			Description: "收件箱会话超过此时间无客服响应标记为 overdue（秒）",
			ValueType:   "duration", DefaultValue: "1800", Min: strPtr("300"), Max: strPtr("172800"), Step: strPtr("60")},
		{Group: "session", Key: "inbox_default_staff_load_limit", Name: "客服默认负载上限",
			Description: "收件箱分配给单个客服的默认会话负载上限",
			ValueType:   "int", DefaultValue: "30", Min: strPtr("1"), Max: strPtr("200"), Step: strPtr("5")},

		{Group: "cache", Key: "memo_ttl", Name: "安装 memo TTL",
			Description: "系统安装信息缓存的有效期（秒）",
			ValueType:   "duration", DefaultValue: "2", Min: strPtr("1"), Max: strPtr("300"), Step: strPtr("1")},
		{Group: "cache", Key: "platform_cache_ttl", Name: "平台缓存 TTL",
			Description: "平台信息 API 结果缓存有效期（秒）",
			ValueType:   "duration", DefaultValue: "20", Min: strPtr("1"), Max: strPtr("3600"), Step: strPtr("1")},
		{Group: "cache", Key: "translation_cache_max_entries", Name: "翻译缓存最大条目",
			Description: "翻译结果内存缓存的最大条目数",
			ValueType:   "int", DefaultValue: "100000", Min: strPtr("1000"), Max: strPtr("10000000"), Step: strPtr("1000")},

		{Group: "agent_llm", Key: "vote_agreement_threshold", Name: "投票一致阈值",
			Description: "多 LLM 投票一致性判断阈值（0-1）",
			ValueType:   "float", DefaultValue: "0.80", Min: strPtr("0.5"), Max: strPtr("1.0"), Step: strPtr("0.05")},
		{Group: "agent_llm", Key: "default_health_check_interval", Name: "健康检查间隔",
			Description: "LLM Provider 熔断器健康检查周期（秒）",
			ValueType:   "duration", DefaultValue: "30", Min: strPtr("5"), Max: strPtr("600"), Step: strPtr("5")},
		{Group: "agent_llm", Key: "default_circuit_open_duration", Name: "熔断器熔断时长",
			Description: "LLM Provider 熔断后保持 open 状态的时长（秒）",
			ValueType:   "duration", DefaultValue: "60", Min: strPtr("10"), Max: strPtr("3600"), Step: strPtr("10")},
		{Group: "agent_llm", Key: "default_health_check_timeout", Name: "健康检查超时",
			Description: "LLM Provider 健康检查请求的超时（秒）",
			ValueType:   "duration", DefaultValue: "5", Min: strPtr("1"), Max: strPtr("60"), Step: strPtr("1")},
		{Group: "agent_llm", Key: "default_failure_threshold", Name: "熔断失败阈值",
			Description: "LLM Provider 连续失败多少次后触发熔断",
			ValueType:   "int", DefaultValue: "5", Min: strPtr("1"), Max: strPtr("50"), Step: strPtr("1")},
		{Group: "agent_llm", Key: "default_http_timeout", Name: "默认 HTTP 超时",
			Description: "LLM 客户端 HTTP 请求默认超时（秒）",
			ValueType:   "duration", DefaultValue: "180", Min: strPtr("5"), Max: strPtr("600"), Step: strPtr("5")},
		{Group: "agent_llm", Key: "db_sink_stop_deadline", Name: "DB Sink 停止截止",
			Description: "Trace DB Sink 停止时等待的最大时间（秒）",
			ValueType:   "duration", DefaultValue: "3", Min: strPtr("1"), Max: strPtr("60"), Step: strPtr("1")},
		{Group: "agent_llm", Key: "provider_failover_policy", Name: "LLM 降级策略（整份 JSON）",
			Description: "按部署覆盖 ProviderFailover 的整份策略：config 里 >0/非空的字段逐项覆盖上面四条 default_* 旋钮；scenarios 是整表替换，少写一个场景不会报错，那个意图改由调度路由给候选。读路径在 internal/aiagent/llm/provider_failover.go 的 LoadPolicy，每 tick 走参数中心 60s 缓存；JSON 非法时整份回落内置默认并打 Warn",
			ValueType:   "string", DefaultValue: `{"config":{"health_check_interval":30,"failure_threshold":5,"circuit_open_duration":60,"degraded_latency_ms":3000,"local_fallback_provider":"default","template_reply":"抱歉，当前服务暂时繁忙，请稍后再试或联系人工客服。","health_check_path":"/health"},"scenarios":{"intent_recognize":["default","deepseek","qwen"],"sop_reply":["default","gpt-4o","glm-4"],"objection":["default","gpt-4o","glm-4"],"friendly_chat":["default","deepseek"],"long_summary":["default","kimi","qwen"],"high_quality":["default","gpt-4o","glm-4"],"low_cost":["default","deepseek"]}}`,
			Category: "LLM"},
		{Group: "agent_llm", Key: "default_semantic_threshold", Name: "语义缓存阈值",
			Description: "FAQ 语义缓存 Tier2 命中相似度阈值（0-1），只在 cache.faq_answer_enabled 为真时有人读。契约只允许调紧：小于 0.95 的值会被构造器抬回 0.95，因此填 0.8 与填 0.95 效果相同",
			ValueType:   "float", DefaultValue: "0.95", Min: strPtr("0.5"), Max: strPtr("1.0"), Step: strPtr("0.05")},

		{Group: "embedding", Key: "global_override", Name: "全局 Embedding 提供商覆盖（整份 JSON）",
			Description: "整份 JSON：{enabled,base_url,api_key,model}。enabled 为真且 base_url 非空时，EmbeddingService.DefaultConfig 用它顶掉 config.yaml/env 那一层，指向云端 OpenAI 兼容端点；关掉只需把 enabled 写成 false。维度硬约束 1024（pgvector 兼容），非 1024 维模型在调用侧强制回落并告警。api_key 落库前已按 llm_providers 同一套加密，页面上看到的是密文。读路径在 internal/aiagent/llm/embedding_global_config.go，写路径由管理端 PUT /api/llm/embedding-config 走本条（带操作者审计）",
			ValueType:   "string", DefaultValue: `{"enabled":false,"base_url":"","api_key":"","model":""}`,
			Category: "LLM"},

		{Group: "knowledge", Key: "max_upload_file_size", Name: "知识库上传大小上限",
			Description: "知识库文档上传的最大文件大小（字节）",
			ValueType:   "int", DefaultValue: "52428800", Min: strPtr("1048576"), Max: strPtr("524288000"), Step: strPtr("1048576")},
		{Group: "knowledge", Key: "merchant_knowledge_max_len", Name: "商户知识库内容上限",
			Description: "外部知识库导入单条内容的最大字符数",
			ValueType:   "int", DefaultValue: "2000", Min: strPtr("100"), Max: strPtr("10000"), Step: strPtr("100")},

		{Group: "wechat", Key: "chat_ws_ping_period", Name: "微信 WS Ping 周期（未接线）",
			Description: "【当前不生效，改了也没人读】internal/controller/chat_ws.go 的 chatWSPingPeriod 有读取点，但承载它的 internal/router/ws.go RegisterWSRoutes 全树零调用方——GET /ws/chat 从未注册，实际落到 SPA 的 NoRoute 兜底。另：后端没有微信渠道 WS 客户端，internal/channelbot 下只有 core/qq/telegram/whatsapp",
			ValueType:   "duration", DefaultValue: "30", Min: strPtr("5"), Max: strPtr("120"), Step: strPtr("1")},
		{Group: "wechat", Key: "chat_ws_pong_wait", Name: "微信 WS Pong 等待（未接线）",
			Description: "【当前不生效，改了也没人读】同上，chatWSPongWait 所在的 /ws/chat 路由从未注册",
			ValueType:   "duration", DefaultValue: "60", Min: strPtr("10"), Max: strPtr("300"), Step: strPtr("1")},
		{Group: "wechat", Key: "chat_ws_write_wait", Name: "微信 WS 写等待（未接线）",
			Description: "【当前不生效，改了也没人读】同上，chatWSWriteWait 所在的 /ws/chat 路由从未注册",
			ValueType:   "duration", DefaultValue: "10", Min: strPtr("1"), Max: strPtr("60"), Step: strPtr("1")},

		{Group: "inbox_sales", Key: "tg_lead_opportunity_threshold", Name: "Telegram 线索机会阈值",
			Description: "Telegram 线索识别判定为有机会的最低分数",
			ValueType:   "int", DefaultValue: "40", Min: strPtr("5"), Max: strPtr("200"), Step: strPtr("1")},
		{Group: "lead", Key: "llm_refine_enabled", Name: "线索LLM复核开关", DefaultValue: "true", ValueType: "bool", Category: "线索挖掘", Description: "开启后线索/商机判定走 LLM 行业无关判别，关键词打分仅作兜底"},
		{Group: "lead", Key: "industry_profile", Name: "行业画像", DefaultValue: "", ValueType: "string", Category: "线索挖掘", Description: "一段自由文本描述本站业务（如：装修公司，主营业内全包/半包家装，面向抖音业主），LLM 线索判别按此理解行业语义"},
		{Group: "inbox_sales", Key: "unified_miner_lead_threshold", Name: "统一挖掘线索阈值",
			Description: "统一线索挖掘判定为有效线索的最低分数",
			ValueType:   "int", DefaultValue: "40", Min: strPtr("5"), Max: strPtr("200"), Step: strPtr("1")},
		{Group: "inbox_sales", Key: "preview_sample_limit", Name: "合并预览采样上限",
			Description: "OneID 合并预览的最大采样数",
			ValueType:   "int", DefaultValue: "20", Min: strPtr("1"), Max: strPtr("100"), Step: strPtr("1")},
		{Group: "inbox_sales", Key: "geo_lead_preview_max_len", Name: "Geo 线索洞察上限",
			Description: "Trace Learning 洞察返回的最大字符数",
			ValueType:   "int", DefaultValue: "200", Min: strPtr("10"), Max: strPtr("5000"), Step: strPtr("50")},

		{Group: "misc", Key: "deepl_timeout", Name: "DeepL 翻译超时",
			Description: "DeepL 翻译 API 请求超时（秒）",
			ValueType:   "duration", DefaultValue: "30", Min: strPtr("5"), Max: strPtr("300"), Step: strPtr("5")},
		{Group: "misc", Key: "reply_sem_timeout", Name: "回复语义超时",
			Description: "Webhook AI 回复语义分析超时（秒）",
			ValueType:   "duration", DefaultValue: "5", Min: strPtr("1"), Max: strPtr("60"), Step: strPtr("1")},
		{Group: "misc", Key: "ownership_cache_ttl", Name: "归属缓存 TTL",
			Description: "权限归属检查的结果缓存有效期（秒）",
			ValueType:   "duration", DefaultValue: "5", Min: strPtr("1"), Max: strPtr("300"), Step: strPtr("1")},
		{Group: "misc", Key: "summary_stale_threshold", Name: "Dashboard 摘要过期阈值",
			Description: "Dashboard SSE 摘要数据超过此时间视为过期需刷新（秒）",
			ValueType:   "duration", DefaultValue: "600", Min: strPtr("60"), Max: strPtr("3600"), Step: strPtr("30")},
		{Group: "misc", Key: "agentloop_history_max_candidates", Name: "AgentLoop 历史最大候选",
			Description: "AgentLoop 召回的历史对话最大候选数",
			ValueType:   "int", DefaultValue: "200", Min: strPtr("10"), Max: strPtr("10000"), Step: strPtr("10")},

		// ---- lock 组：锁与幂等 TTL（阶段 2c）----
		// 这一组与其它组性质不同：这些 TTL 是正确性参数而不是调优项，写错的
		// 结果是死锁、并发重复落库或重复回复，所以每条 Description 都写清
		// 「改小/改大会出什么事」，而不是只写「是什么」。
		{Group: "lock", Key: "inbox_human_ttl", Name: "人工接管锁 TTL",
			Description: "收件箱人工接管锁的存活时间（秒）。锁到期后该会话的入站消息会被 AI 继续处理——写小＝人工还没说完就被交回给 AI，写大＝人工忘记点「结束接管」后长时间无法自动恢复",
			ValueType:   "duration", DefaultValue: "86400", Min: strPtr("60"), Max: strPtr("604800"), Step: strPtr("60"), Restart: false},
		{Group: "lock", Key: "inbox_pending_ttl", Name: "入站待处理队列 TTL",
			Description: "AI 防抖期间暂存入站消息的存活时间（秒）。写小＝防抖窗口还没走完消息就消失了，客户那句话直接丢失且无投递痕迹",
			ValueType:   "duration", DefaultValue: "300", Min: strPtr("30"), Max: strPtr("86400"), Step: strPtr("30"), Restart: false},
		{Group: "lock", Key: "inbox_content_dedup_ttl", Name: "入站内容去重窗口",
			Description: "入口「渠道+发送者+内容」去重键的存活时间（秒）。写小＝平台重发与出站回显这类正常重复会漏过，写大＝客户隔很久把同一句话又说了一遍会被当成重复而吞掉",
			ValueType:   "duration", DefaultValue: "300", Min: strPtr("10"), Max: strPtr("86400"), Step: strPtr("30"), Restart: false},
		{Group: "lock", Key: "ingest_lock_ttl", Name: "入站落库锁 TTL",
			Description: "同一会话入站落库互斥锁的存活时间（秒）。锁只在落库函数执行期间持有，写小＝长事务没跑完锁就被别人抢走导致并发重复落库，写大＝进程崩溃后该会话被挡住直到 TTL 自然过期",
			ValueType:   "duration", DefaultValue: "25", Min: strPtr("5"), Max: strPtr("600"), Step: strPtr("5"), Restart: false},
		{Group: "lock", Key: "ai_processing_ttl", Name: "AI 处理中标记 TTL",
			Description: "「AI 正在处理」排他标记的存活时间（秒），推理期间到达的新消息靠它避免被补触发第二次。写小＝重复回复，写大＝AI 进程崩了之后该会话长时间不再响应",
			ValueType:   "duration", DefaultValue: "120", Min: strPtr("10"), Max: strPtr("3600"), Step: strPtr("10"), Restart: false},
		{Group: "lock", Key: "message_hub_idem_ttl", Name: "消息中台幂等 TTL",
			Description: "消息中台投递幂等键的存活时间（秒），同一 msgID 在此窗口内重复投递会被判重丢弃。注意它在账号服务构造期读取，改动要重启才对已启动的账号生效",
			ValueType:   "duration", DefaultValue: "86400", Min: strPtr("60"), Max: strPtr("604800"), Step: strPtr("60"), Restart: true},
		{Group: "lock", Key: "ai_lock_ttl", Name: "AI 会话锁 TTL（未接线）",
			Description: "【当前不生效，改了也没人读】InboxAILockKey 那把锁的兜底 TTL（秒）。tryAcquireAILock / ReleaseAILock / IsSessionAIBusy 三个函数整条生产链路都没人调用（源文件自带 //nolint:unused 标注），真正在跑的并发闸是上面 ai_processing_ttl 那条；要启用这套锁得先接 callers，再接本参数",
			ValueType:   "duration", DefaultValue: "15", Min: strPtr("5"), Max: strPtr("300"), Step: strPtr("5"), Restart: false},

		// ── channelbot 组：渠道侧的长度/条数上限与外部依赖超时 ──────────────
		// 平台自身也有硬上限（QQ 2000 / TG 4096 / inline keyboard 100 行 8 钮），
		// 调大超过平台限制只会让平台侧报错，调小则提前分批发送。
		{Group: "channelbot", Key: "qq_message_max_len", Name: "QQ 单条消息长度上限",
			Description: "QQ 渠道单条文本消息的最大长度（字符）。超出即自动分段发送，返回首段 msg_id。写大超过平台 2000 上限会被平台直接拒收而本地毫不知情，写小则一条回复被拆成很多条、观感碎",
			ValueType:   "int", DefaultValue: "2000", Min: strPtr("1"), Max: strPtr("2000"), Step: strPtr("1"), Restart: false},
		{Group: "channelbot", Key: "tg_message_max_length", Name: "TG 单条消息长度上限",
			Description: "Telegram 渠道单条文本消息的最大长度（字符）。超出即自动分段发送，返回首段 message_id。写大超过平台 4096 上限会被平台直接拒收，写小则一条回复被拆成很多条",
			ValueType:   "int", DefaultValue: "4096", Min: strPtr("1"), Max: strPtr("4096"), Step: strPtr("1"), Restart: false},
		{Group: "channelbot", Key: "tg_inline_rows_max", Name: "TG inline 键盘行数上限",
			Description: "Telegram inline keyboard 的最大行数。超出即截断（多出来的按钮直接消失）。写大超过平台 100 行上限会让整个键盘被平台拒收导致按钮全部消失，比截断更糟",
			ValueType:   "int", DefaultValue: "100", Min: strPtr("1"), Max: strPtr("100"), Step: strPtr("1"), Restart: false},
		{Group: "channelbot", Key: "tg_inline_buttons_per_row_max", Name: "TG inline 键盘每行按钮数上限",
			Description: "Telegram inline keyboard 每一行的最大按钮数。超出即截断。写大超过平台 8 个上限会让整个键盘被拒收导致按钮全部消失",
			ValueType:   "int", DefaultValue: "8", Min: strPtr("1"), Max: strPtr("8"), Step: strPtr("1"), Restart: false},
		{Group: "channelbot", Key: "http_timeout", Name: "渠道外部依赖 HTTP 超时",
			Description: "channelbot 各子包（QQ/TG/WhatsApp）访问平台 API 的默认 HTTP 超时（秒）。构造期读一次，改完需重启。写大＝外部依赖挂起时请求 goroutine 长时间占着不放，写小＝平台侧慢一点就误判超时（Telegram 的长轮询 getUpdates 天然需要几十秒，别把它调小）",
			ValueType:   "duration", DefaultValue: "30", Min: strPtr("1"), Max: strPtr("120"), Step: strPtr("1"), Restart: true},

		// ── sse 组：业务侧 SSE 连接参数 ───────────────────────────────────
		// 注意与 bridge.sse_* 区分：那两条管 bridge 长连接，这一组管业务 SSE Hub。
		{Group: "sse", Key: "heartbeat_interval", Name: "SSE 心跳间隔",
			Description: "业务 SSE 连接发送心跳注释帧的间隔（秒）。写大＝反代/CDN 的 proxy_read_timeout（通常 60s）会切断长连接，写小＝空连接也持续占用带宽。0 值会让 time.NewTicker(0) 直接 panic，故非法值一律回落兜底",
			ValueType:   "duration", DefaultValue: "15", Min: strPtr("1"), Max: strPtr("60"), Step: strPtr("1"), Restart: false},
		{Group: "sse", Key: "max_conn_per_ip", Name: "SSE 单 IP 连接数上限",
			Description: "同一个来源 IP 允许同时打开的 SSE 连接数。这是防单点刷连接的闸。写大＝一个 IP 能把连接池占满挤掉正常用户，写小＝NAT/办公室出口共用 IP 的场景下多名正常用户会互相挤掉。0 会把所有访客一次性挡在门外",
			ValueType:   "int", DefaultValue: "5", Min: strPtr("1"), Max: strPtr("200"), Step: strPtr("1"), Restart: false},
		{Group: "sse", Key: "client_buffer_size", Name: "SSE 客户端事件缓冲",
			Description: "每个 SSE 连接本地事件队列的容量（条）。写大＝每个连接按上限常驻内存，写小＝事件突发时更早触发丢弃/断链。0 会让缓冲退化为同步信道，一个慢客户端就能堵死整个广播。构造期读一次，改完需重启",
			ValueType:   "int", DefaultValue: "100", Min: strPtr("1"), Max: strPtr("10000"), Step: strPtr("1"), Restart: true},

		// ── bridge 组补充：回放 backlog 与总线缓冲 ────────────────────────
		// bridge.sse_heartbeat_interval / sse_max_stream_duration 更早就已 DB 驱动，
		// 这里补的是同文件里另外两个此前写死的。
		{Group: "bridge", Key: "sse_max_backlog_events", Name: "bridge SSE 回放 backlog 上限",
			Description: "每个 bridge SSE 连接为断线重连保留的回放事件数（条）。写大＝每个长连接按上限常驻内存，写小＝客户端重连后更早开始丢事件（表现为「中间几条消息没收到」）",
			ValueType:   "int", DefaultValue: "1000", Min: strPtr("1"), Max: strPtr("100000"), Step: strPtr("1"), Restart: false},
		{Group: "bridge", Key: "sse_bus_buffer_size", Name: "bridge SSE 总线缓冲",
			Description: "bridge SSE 事件总线的 channel 容量（条）。写大＝一次事件洪峰更不容易阻塞发布方，代价是常驻内存；写小＝洪峰时发布方被阻塞。0 会让总线退化为同步信道，一个慢消费者就能堵死所有出站投递。构造期读一次，改完需重启",
			ValueType:   "int", DefaultValue: "100", Min: strPtr("1"), Max: strPtr("100000"), Step: strPtr("1"), Restart: true},
	}
}
