package service

// ParamDef 单个参数定义（用于 Seed 初始化）
type ParamDef struct {
	Group        string
	Key          string
	Name         string
	Description  string
	ValueType    string
	DefaultValue string
	Min          *string
	Max          *string
	Step         *string
	ReadOnly     bool
	Restart      bool
	Category     string
}

func strPtr(s string) *string { return &s }

// DefaultParamDefs 返回全部默认参数定义
//
// 来源：项目内 ~60 处硬编码 const（bridge/handler_http.go、
// knowledge/service/constants.go、smart_cs_orchestrator.go、
// customer_session.go、cache/memory.go 等）。
//
// 设计原则：
//  1. 每一条对应一个现存的硬编码 const
//  2. Group 按业务域划分：bridge / knowledge / agent_llm / smart_cs /
//     session / cache / pagination / wecom / telemetry / sales / misc
//  3. Min/Max/Step 基于参数语义的合理范围（用于 UI slider/number input）
func DefaultParamDefs() []ParamDef {
	return []ParamDef{

		{Group: "permission", Key: "role_permissions_json", Name: "角色权限矩阵",
			Description: "JSON: {角色码: [权限项]}；权限项支持 module.* 通配；admin 恒全权不走此配置",
			ValueType:   "string", DefaultValue: `{"customer_service":["cards.*","shortlinks.*","clues.*","autoreply.*"],"staff":["cards.view","shortlinks.view","clues.view"]}`, Category: "权限"},

		{Group: "reach", Key: "global_per_user_daily_limit", Name: "单客户全管线日触达上限",
			Description: "同一客户被全部触达管线共享的每日（CST 自然日）触达上限；0=禁用该层",
			ValueType:   "int", DefaultValue: "3", Min: strPtr("0"), Max: strPtr("50"), Category: "触达"},

		{Group: "bridge", Key: "polling_max_timeout", Name: "轮询最大超时",
			Description: "客户端 HTTP 长轮询允许的最长等待时间（秒），超时由服务端主动返回",
			ValueType:   "duration", DefaultValue: "500", Min: strPtr("10"), Max: strPtr("3600"), Step: strPtr("5")},
		{Group: "bridge", Key: "polling_default_timeout", Name: "轮询默认超时",
			Description: "客户端未指定 timeout 参数时的默认等待时间（秒）",
			ValueType:   "duration", DefaultValue: "30", Min: strPtr("5"), Max: strPtr("120"), Step: strPtr("1")},
		{Group: "bridge", Key: "ingest_max_body_bytes", Name: "Ingest 请求体上限",
			Description: "bridge/ingest 单次请求体最大字节数",
			ValueType:   "int", DefaultValue: "4194304", Min: strPtr("1048576"), Max: strPtr("67108864")},
		{Group: "bridge", Key: "ingest_max_messages", Name: "Ingest 单次消息数上限",
			Description: "单次上报最多携带的消息条数",
			ValueType:   "int", DefaultValue: "200", Min: strPtr("10"), Max: strPtr("2000"), Step: strPtr("10")},
		{Group: "bridge", Key: "sse_heartbeat_interval", Name: "SSE 心跳间隔",
			Description: "SSE 空闲时服务端向客户端发送心跳包的间隔（秒）",
			ValueType:   "duration", DefaultValue: "15", Min: strPtr("5"), Max: strPtr("60"), Step: strPtr("1")},
		{Group: "bridge", Key: "max_reply_content_bytes", Name: "回复内容截断上限",
			Description: "AI 回复内容超过此字节数时截断（防止超长大文本撑爆渠道）",
			ValueType:   "int", DefaultValue: "4096", Min: strPtr("1024"), Max: strPtr("65536"), Step: strPtr("256")},
		{Group: "bridge", Key: "max_ack_msg_ids", Name: "ACK 单次消息ID数上限",
			Description: "客户端一次 ACK 最多携带的消息 ID 数",
			ValueType:   "int", DefaultValue: "500", Min: strPtr("50"), Max: strPtr("5000"), Step: strPtr("50")},
		{Group: "bridge", Key: "online_grace_window", Name: "在线状态宽限窗口",
			Description: "渠道账号心跳丢失后仍判定为在线的宽限时间（秒）",
			ValueType:   "duration", DefaultValue: "30", Min: strPtr("10"), Max: strPtr("300"), Step: strPtr("5")},

		{Group: "knowledge", Key: "default_top_k", Name: "默认 Top-K 检索数",
			Description: "向量检索返回的候选文档数",
			ValueType:   "int", DefaultValue: "5", Min: strPtr("1"), Max: strPtr("50"), Step: strPtr("1")},
		{Group: "knowledge", Key: "similarity_threshold", Name: "相似度阈值",
			Description: "向量检索相似度低于此值视为无相关内容（0-1）",
			ValueType:   "float", DefaultValue: "0.5", Min: strPtr("0.1"), Max: strPtr("0.95"), Step: strPtr("0.05")},
		{Group: "knowledge", Key: "chunk_preview_max_len", Name: "分片内容预览长度",
			Description: "检索结果 Content 字段截断长度",
			ValueType:   "int", DefaultValue: "500", Min: strPtr("100"), Max: strPtr("5000"), Step: strPtr("50")},
		{Group: "knowledge", Key: "max_search_list_size", Name: "检索扫描上限",
			Description: "BM25-lite 兜底路径扫描的最大条目数",
			ValueType:   "int", DefaultValue: "1000", Min: strPtr("100"), Max: strPtr("100000"), Step: strPtr("100")},
		{Group: "knowledge", Key: "bm25_scan_limit", Name: "BM25 文本匹配上限",
			Description: "BM25 关键词匹配扫描的最大分片数",
			ValueType:   "int", DefaultValue: "10000", Min: strPtr("1000"), Max: strPtr("500000"), Step: strPtr("1000")},
		{Group: "knowledge", Key: "embedding_dimension", Name: "Embedding 维度",
			Description: "向量嵌入维度（bge-m3 默认 1024）",
			ValueType:   "int", DefaultValue: "1024", Min: strPtr("128"), Max: strPtr("8192"), ReadOnly: true},
		{Group: "knowledge", Key: "async_processing_timeout", Name: "异步处理超时",
			Description: "文档异步处理（分片+embedding+索引）总超时（秒）",
			ValueType:   "duration", DefaultValue: "900", Min: strPtr("60"), Max: strPtr("7200"), Step: strPtr("60")},
		{Group: "knowledge", Key: "external_import_timeout", Name: "外部导入超时",
			Description: "飞书/Notion 外部导入总超时（秒）",
			ValueType:   "duration", DefaultValue: "1800", Min: strPtr("60"), Max: strPtr("7200"), Step: strPtr("60")},
		{Group: "knowledge", Key: "ssrf_check_timeout", Name: "SSRF 防护超时",
			Description: "外部 URL SSRF 校验的单次 HTTP 超时（秒）",
			ValueType:   "duration", DefaultValue: "5", Min: strPtr("1"), Max: strPtr("60"), Step: strPtr("1")},
		{Group: "knowledge", Key: "embedding_max_batch", Name: "Embedding 最大批大小",
			Description: "单次 embedding 向量化调用的最大文本批数",
			ValueType:   "int", DefaultValue: "64", Min: strPtr("1"), Max: strPtr("1024"), Step: strPtr("8")},

		{Group: "agent_llm", Key: "temperature", Name: "LLM Temperature",
			Description: "采样温度，越大输出越发散（0-2）",
			ValueType:   "float", DefaultValue: "0.7", Min: strPtr("0.1"), Max: strPtr("2.0"), Step: strPtr("0.1")},
		{Group: "agent_llm", Key: "max_tokens", Name: "LLM Max Tokens",
			Description: "单次 LLM 调用最大生成 token 数",
			ValueType:   "int", DefaultValue: "1000", Min: strPtr("64"), Max: strPtr("8192"), Step: strPtr("64")},
		{Group: "agent_llm", Key: "top_p", Name: "LLM Top-P",
			Description: "核采样概率阈值（0-1）",
			ValueType:   "float", DefaultValue: "0.9", Min: strPtr("0.5"), Max: strPtr("1.0"), Step: strPtr("0.05")},
		{Group: "agent_llm", Key: "request_timeout", Name: "LLM 请求超时",
			Description: "单次 LLM HTTP 请求超时（秒）",
			ValueType:   "duration", DefaultValue: "60", Min: strPtr("5"), Max: strPtr("600"), Step: strPtr("5")},
		{Group: "agent_llm", Key: "max_retries", Name: "LLM 最大重试",
			Description: "LLM 调用失败后自动重试次数",
			ValueType:   "int", DefaultValue: "3", Min: strPtr("0"), Max: strPtr("10"), Step: strPtr("1")},
		{Group: "agent_llm", Key: "agent_loop_drift_factor", Name: "AgentLoop 漂移因子",
			Description: "智能体循环步数相对阈值的放宽倍数（超过阈值×factor 触发降级）",
			ValueType:   "float", DefaultValue: "2.5", Min: strPtr("1.0"), Max: strPtr("10.0"), Step: strPtr("0.1")},
		{Group: "agent_llm", Key: "minor_llm_threshold", Name: "轻量 LLM 意图阈值",
			Description: "意图识别置信度低于此值时只调用轻量模型（非完整 LLM）",
			ValueType:   "float", DefaultValue: "0.6", Min: strPtr("0.3"), Max: strPtr("0.95"), Step: strPtr("0.05")},
		{Group: "agent_llm", Key: "geo_max_tokens_per_call", Name: "Geo LLM 单调 Token 上限",
			Description: "内容分析 Geo 场景单次 LLM 调用的最大 token",
			ValueType:   "int", DefaultValue: "4000", Min: strPtr("512"), Max: strPtr("32768"), Step: strPtr("256")},

		{Group: "smart_cs", Key: "confidence_threshold", Name: "智能客服置信度阈值",
			Description: "置信度高于此值才走自动 AI 回复，否则转人工",
			ValueType:   "float", DefaultValue: "0.7", Min: strPtr("0.3"), Max: strPtr("0.99"), Step: strPtr("0.05")},
		{Group: "smart_cs", Key: "enable_auto_reply", Name: "开启自动回复",
			Description: "是否允许智能体自动回复（false 时全部转人工）",
			ValueType:   "bool", DefaultValue: "true"},
		{Group: "smart_cs", Key: "max_ai_consecutive", Name: "AI 连续回复上限",
			Description: "同一会话内 AI 连续回复超过此次数后强制转人工",
			ValueType:   "int", DefaultValue: "10", Min: strPtr("2"), Max: strPtr("50"), Step: strPtr("1")},

		// human_task.handoff_first_response_minutes（T-P3-03）：键名这里是一串字面量、
		// 服务侧读的是 service.HumanTaskConfigGroup / HumanTaskHandoffSlaKey 两个常量，
		// 两边打错任意一处都**不会报错**，只会让运维改参数永远不生效（GetInt 安静回退默认值）。
		// 所以一致性由 TestHumanTaskSeedKeyMatchesServiceConstants 逐字锁住。
		{Group: "human_task", Key: "handoff_first_response_minutes", Name: "转人工首响时限（分钟）",
			Description: "会话转人工后坐席首次响应的时限，超时即计入人工待办逾期读数；1~1440 之外一律回退默认 5 分钟",
			ValueType:   "int", DefaultValue: "5", Min: strPtr("1"), Max: strPtr("1440"), Step: strPtr("1")},

		{Group: "session", Key: "active_ttl", Name: "会话活跃 TTL",
			Description: "无任何消息交互超过此时间后会话自动关闭（秒）",
			ValueType:   "duration", DefaultValue: "86400", Min: strPtr("300"), Max: strPtr("2592000"), Step: strPtr("3600")},
		{Group: "session", Key: "idle_ttl", Name: "MCP 会话空闲 TTL",
			Description: "MCP Server 会话无活动超过此时间后过期（秒）",
			ValueType:   "duration", DefaultValue: "1800", Min: strPtr("60"), Max: strPtr("86400"), Step: strPtr("60")},
		{Group: "session", Key: "max_delay_seconds", Name: "营销触达延迟上限",
			Description: "触达流水线排程允许的最大延迟（秒），超过视为放弃",
			ValueType:   "duration", DefaultValue: "300", Min: strPtr("30"), Max: strPtr("3600"), Step: strPtr("10")},

		{Group: "cache", Key: "max_keys", Name: "内存缓存最大键数",
			Description: "进程内内存缓存的最大条目数（超过会触发 LRU 淘汰）",
			ValueType:   "int", DefaultValue: "10000", Min: strPtr("1000"), Max: strPtr("1000000"), Step: strPtr("1000")},
		{Group: "cache", Key: "faq_ttl", Name: "FAQ 缓存 TTL",
			Description: "FAQ 语义缓存有效期（秒）",
			ValueType:   "duration", DefaultValue: "300", Min: strPtr("60"), Max: strPtr("86400"), Step: strPtr("60")},
		{Group: "cache", Key: "faq_decay_max_batch", Name: "FAQ 衰减批量",
			Description: "后台 FAQ 分数衰减任务每轮处理的最大条目",
			ValueType:   "int", DefaultValue: "1000", Min: strPtr("100"), Max: strPtr("100000"), Step: strPtr("100")},

		{Group: "pagination", Key: "page_max_size", Name: "单页最大条数",
			Description: "列表接口允许的 limit 上限（超过此值强制截断）",
			ValueType:   "int", DefaultValue: "100", Min: strPtr("10"), Max: strPtr("10000"), Step: strPtr("10")},
		{Group: "pagination", Key: "page_default_size", Name: "默认分页大小",
			Description: "列表接口 limit 未指定时的默认值",
			ValueType:   "int", DefaultValue: "20", Min: strPtr("5"), Max: strPtr("500"), Step: strPtr("5")},
		{Group: "pagination", Key: "cursor_page_size", Name: "游标分页大小",
			Description: "游标分页（Cursor）每批拉取的数量",
			ValueType:   "int", DefaultValue: "100", Min: strPtr("10"), Max: strPtr("1000"), Step: strPtr("10")},

		{Group: "wecom", Key: "error_rate_degrade", Name: "错误率降级阈值",
			Description: "企微接口错误率超过此值触发降级到备用通道（0-1）",
			ValueType:   "float", DefaultValue: "0.3", Min: strPtr("0.05"), Max: strPtr("0.95"), Step: strPtr("0.05")},
		{Group: "wecom", Key: "quota_degrade", Name: "配额降级阈值",
			Description: "企微消息使用率超过此比例触发限流（0-1）",
			ValueType:   "float", DefaultValue: "0.9", Min: strPtr("0.5"), Max: strPtr("1.0"), Step: strPtr("0.05")},

		{Group: "telemetry", Key: "node_health_window", Name: "节点健康检查窗口",
			Description: "节点最近 24 小时的健康心跳统计窗口（秒）",
			ValueType:   "duration", DefaultValue: "86400", Min: strPtr("3600"), Max: strPtr("604800"), Step: strPtr("3600")},
		{Group: "telemetry", Key: "trace_sink_buffer", Name: "Trace Sink 缓冲",
			Description: "追踪采集缓冲队列容量（超过丢弃低优先级事件）",
			ValueType:   "int", DefaultValue: "8192", Min: strPtr("256"), Max: strPtr("524288"), Step: strPtr("256")},
		{Group: "telemetry", Key: "geo_position_window", Name: "Geo 位置统计窗口",
			Description: "Geo 地理位置统计的滑动窗口大小",
			ValueType:   "int", DefaultValue: "20", Min: strPtr("5"), Max: strPtr("100"), Step: strPtr("1")},
		{Group: "telemetry", Key: "feature_flag_poll_interval", Name: "Feature Flag 轮询间隔",
			Description: "内存内存缓存刷新的轮询周期（秒）",
			ValueType:   "duration", DefaultValue: "5", Min: strPtr("1"), Max: strPtr("300"), Step: strPtr("1")},

		{Group: "sales", Key: "insight_limit", Name: "销售洞察条数",
			Description: "sales insight 返回的最大建议条数",
			ValueType:   "int", DefaultValue: "3", Min: strPtr("1"), Max: strPtr("20"), Step: strPtr("1")},
		{Group: "sales", Key: "identity_max_attempts", Name: "客户身份合并重试上限",
			Description: "CustomerIdentity 身份合并的最大重试次数",
			ValueType:   "int", DefaultValue: "8", Min: strPtr("1"), Max: strPtr("50"), Step: strPtr("1")},

		{Group: "misc", Key: "visitor_token_ttl", Name: "访客 Token TTL",
			Description: "未登录访客的身份 Token 有效期（秒）",
			ValueType:   "duration", DefaultValue: "604800", Min: strPtr("3600"), Max: strPtr("2592000"), Step: strPtr("3600")},
		{Group: "misc", Key: "sso_cookie_ttl", Name: "SSO Cookie TTL",
			Description: "SSO 单点登录 cookie 的有效期（秒）",
			ValueType:   "duration", DefaultValue: "300", Min: strPtr("60"), Max: strPtr("86400"), Step: strPtr("60")},
		{Group: "misc", Key: "heartbeat_interval", Name: "平台心跳间隔",
			Description: "向平台发送心跳的周期（秒）",
			ValueType:   "duration", DefaultValue: "180", Min: strPtr("30"), Max: strPtr("3600"), Step: strPtr("10")},
		{Group: "misc", Key: "polling_lock_stale_threshold", Name: "轮询锁过期阈值",
			Description: "Telegram 等渠道 polling lock 超过此时间未更新视为失效（秒）",
			ValueType:   "duration", DefaultValue: "60", Min: strPtr("10"), Max: strPtr("600"), Step: strPtr("5")},
		{Group: "misc", Key: "domain_check_concurrency", Name: "域名检测并发",
			Description: "域名可用性检查的并发 goroutine 数",
			ValueType:   "int", DefaultValue: "16", Min: strPtr("1"), Max: strPtr("128"), Step: strPtr("1")},
		{Group: "misc", Key: "ab_exposure_buffer", Name: "AB 曝光缓冲",
			Description: "AB 实验曝光事件的批量缓冲大小",
			ValueType:   "int", DefaultValue: "1024", Min: strPtr("64"), Max: strPtr("65536"), Step: strPtr("64")},
		{Group: "misc", Key: "sms_max_retry", Name: "短信最大重试次数",
			Description: "短信发送失败后的重试次数",
			ValueType:   "int", DefaultValue: "3", Min: strPtr("0"), Max: strPtr("10"), Step: strPtr("1")},
		{Group: "misc", Key: "csv_export_max_rows", Name: "CSV 导出最大行数",
			Description: "自定义报表 CSV 导出的单行上限（防止 OOM）",
			ValueType:   "int", DefaultValue: "30000", Min: strPtr("1000"), Max: strPtr("500000"), Step: strPtr("1000")},
		{Group: "misc", Key: "backup_page_size", Name: "备份分页大小",
			Description: "数据库备份导出的分页大小",
			ValueType:   "int", DefaultValue: "1000", Min: strPtr("100"), Max: strPtr("100000"), Step: strPtr("100")},
		{Group: "misc", Key: "text_truncate_max_bytes", Name: "文本截断上限",
			Description: "文本工具通用截断的最大字节数",
			ValueType:   "int", DefaultValue: "8192", Min: strPtr("512"), Max: strPtr("1048576"), Step: strPtr("256")},
		{Group: "misc", Key: "preview_max_len", Name: "消息预览最大长度",
			Description: "消息列表 preview 字段的最大字符长度",
			ValueType:   "int", DefaultValue: "500", Min: strPtr("50"), Max: strPtr("5000"), Step: strPtr("50")},
		{Group: "misc", Key: "sop_scheduler_interval", Name: "SOP Scheduler 扫描间隔",
			Description: "SOP 调度器扫描待触发任务的周期（秒）",
			ValueType:   "duration", DefaultValue: "60", Min: strPtr("5"), Max: strPtr("600"), Step: strPtr("5")},
		{Group: "misc", Key: "sop_max_wait", Name: "SOP Timer 最大等待",
			Description: "SOP 定时器的最大等待时间（超过视为异常）",
			ValueType:   "duration", DefaultValue: "86400", Min: strPtr("3600"), Max: strPtr("2592000"), Step: strPtr("3600")},

		{Group: "channelgw", Key: "ws_register_timeout", Name: "WS 注册超时",
			Description: "Channel Gateway WebSocket 注册握手超时（秒）",
			ValueType:   "duration", DefaultValue: "15", Min: strPtr("5"), Max: strPtr("60"), Step: strPtr("1")},
		{Group: "channelgw", Key: "ws_read_idle_timeout", Name: "WS 读空闲超时",
			Description: "WebSocket 读取空闲超时（秒），超过触发重连",
			ValueType:   "duration", DefaultValue: "90", Min: strPtr("10"), Max: strPtr("600"), Step: strPtr("5")},
		{Group: "channelgw", Key: "ws_write_timeout", Name: "WS 写超时",
			Description: "WebSocket 单次写超时（秒）",
			ValueType:   "duration", DefaultValue: "10", Min: strPtr("1"), Max: strPtr("60"), Step: strPtr("1")},
		{Group: "channelgw", Key: "ws_push_interval", Name: "WS 推送间隔",
			Description: "心跳空闲时 WS 推送消息的最小间隔（秒）",
			ValueType:   "duration", DefaultValue: "2", Min: strPtr("1"), Max: strPtr("10"), Step: strPtr("1")},
		{Group: "channelgw", Key: "ws_pipeline_timeout", Name: "WS Pipeline 超时",
			Description: "WS pipeline 单次批量处理超时（秒）",
			ValueType:   "duration", DefaultValue: "30", Min: strPtr("5"), Max: strPtr("300"), Step: strPtr("5")},

		{Group: "agent_tool", Key: "max_concurrent", Name: "工具最大并发",
			Description: "Agent 工具执行器同时运行的最大并发数",
			ValueType:   "int", DefaultValue: "5", Min: strPtr("1"), Max: strPtr("50"), Step: strPtr("1")},
		{Group: "agent_tool", Key: "max_content_len", Name: "工具输出截断上限",
			Description: "工具返回内容超过此长度时截断",
			ValueType:   "int", DefaultValue: "4000", Min: strPtr("512"), Max: strPtr("65536"), Step: strPtr("256")},
		{Group: "agent_tool", Key: "result_cache_ttl", Name: "工具结果缓存 TTL",
			Description: "工具调用结果在内存中缓存的有效期（秒）",
			ValueType:   "duration", DefaultValue: "60", Min: strPtr("10"), Max: strPtr("3600"), Step: strPtr("5")},
		{Group: "agent_tool", Key: "cooldown_duration", Name: "工具冷却时间",
			Description: "工具失败后自动冷却时间（秒）",
			ValueType:   "duration", DefaultValue: "30", Min: strPtr("5"), Max: strPtr("300"), Step: strPtr("5")},
		{Group: "agent_tool", Key: "fail_threshold", Name: "工具熔断阈值",
			Description: "连续失败多少次后触发熔断",
			ValueType:   "int", DefaultValue: "5", Min: strPtr("1"), Max: strPtr("50"), Step: strPtr("1")},

		{Group: "middleware", Key: "audit_flush_interval", Name: "审计刷盘间隔",
			Description: "审计中间件批量刷盘到 DB 的时间间隔（秒）",
			ValueType:   "duration", DefaultValue: "5", Min: strPtr("1"), Max: strPtr("300"), Step: strPtr("1")},
		{Group: "middleware", Key: "mfa_recent_verify_ttl", Name: "MFA 近验有效期",
			Description: "MFA 二次验证后的宽限期（秒）",
			ValueType:   "duration", DefaultValue: "300", Min: strPtr("60"), Max: strPtr("3600"), Step: strPtr("60")},

		{Group: "confidence", Key: "humanize_default_threshold", Name: "人性化默认阈值",
			Description: "文本人性化判定阈值（0-1）",
			ValueType:   "float", DefaultValue: "0.85", Min: strPtr("0.1"), Max: strPtr("1.0"), Step: strPtr("0.05")},
		{Group: "confidence", Key: "persona_default_threshold", Name: "人设默认阈值",
			Description: "人设匹配判定阈值（0-1）",
			ValueType:   "float", DefaultValue: "0.85", Min: strPtr("0.1"), Max: strPtr("1.0"), Step: strPtr("0.05")},
		{Group: "confidence", Key: "persona_max_retry", Name: "人设最大重试",
			Description: "人设评估失败后最大重试次数",
			ValueType:   "int", DefaultValue: "3", Min: strPtr("0"), Max: strPtr("10"), Step: strPtr("1")},
		{Group: "confidence", Key: "intent_fewshot_min_cos", Name: "意图 Few-Shot 最小余弦",
			Description: "意图识别 Few-Shot 检索最小余弦相似度",
			ValueType:   "float", DefaultValue: "0.7", Min: strPtr("0.1"), Max: strPtr("1.0"), Step: strPtr("0.05")},
		{Group: "confidence", Key: "weak_truth_min_confidence", Name: "弱真值最小置信度",
			Description: "意图指标弱真值判定的最小置信度（0-1）",
			ValueType:   "float", DefaultValue: "0.9", Min: strPtr("0.1"), Max: strPtr("1.0"), Step: strPtr("0.05")},
		{Group: "confidence", Key: "emb_retry_cooldown", Name: "Embedding 重试冷却",
			Description: "Embedding 重试调用的冷却间隔（秒）",
			ValueType:   "duration", DefaultValue: "60", Min: strPtr("5"), Max: strPtr("300"), Step: strPtr("5")},
		{Group: "confidence", Key: "veto_low_rag_threshold", Name: "否决低 RAG 阈值",
			Description: "否决规则触发的最低 RAG 得分阈值",
			ValueType:   "float", DefaultValue: "0.1", Min: strPtr("0"), Max: strPtr("0.5"), Step: strPtr("0.01")},

		{Group: "workflow", Key: "max_subflow_depth", Name: "子流程最大深度",
			Description: "子流程嵌套最大层级，防止无限递归",
			ValueType:   "int", DefaultValue: "5", Min: strPtr("1"), Max: strPtr("30"), Step: strPtr("1")},
		{Group: "workflow", Key: "max_workflow_steps", Name: "工作流最大步数",
			Description: "单个工作流最多可执行的节点数",
			ValueType:   "int", DefaultValue: "1000", Min: strPtr("10"), Max: strPtr("100000"), Step: strPtr("10")},
		{Group: "workflow", Key: "max_running_per_sop", Name: "单 SOP 最大并发",
			Description: "同一个 SOP 模板同时运行的最大实例数",
			ValueType:   "int", DefaultValue: "50", Min: strPtr("1"), Max: strPtr("500"), Step: strPtr("1")},
		{Group: "workflow", Key: "max_executed_node_trace", Name: "执行轨迹最大节点",
			Description: "SOP 执行历史记录最多保留的节点数",
			ValueType:   "int", DefaultValue: "200", Min: strPtr("10"), Max: strPtr("10000"), Step: strPtr("10")},

		{Group: "session", Key: "inbox_overdue_threshold", Name: "收件箱超时阈值",
			Description: "收件箱会话超过此时间无客服响应标记为 overdue（秒）",
			ValueType:   "duration", DefaultValue: "1800", Min: strPtr("300"), Max: strPtr("172800"), Step: strPtr("60")},
		{Group: "session", Key: "inbox_default_staff_load_limit", Name: "客服默认负载上限",
			Description: "收件箱分配给单个客服的默认会话负载上限",
			ValueType:   "int", DefaultValue: "30", Min: strPtr("1"), Max: strPtr("200"), Step: strPtr("5")},

		{Group: "cache", Key: "memo_ttl", Name: "安装 memo TTL",
			Description: "系统安装信息缓存的有效期（秒）",
			ValueType:   "duration", DefaultValue: "2", Min: strPtr("1"), Max: strPtr("300"), Step: strPtr("1")},
		{Group: "cache", Key: "platform_cache_ttl", Name: "平台缓存 TTL",
			Description: "平台信息 API 结果缓存有效期（秒）",
			ValueType:   "duration", DefaultValue: "20", Min: strPtr("1"), Max: strPtr("3600"), Step: strPtr("1")},
		{Group: "cache", Key: "translation_cache_max_entries", Name: "翻译缓存最大条目",
			Description: "翻译结果内存缓存的最大条目数",
			ValueType:   "int", DefaultValue: "100000", Min: strPtr("1000"), Max: strPtr("10000000"), Step: strPtr("1000")},

		{Group: "agent_llm", Key: "vote_agreement_threshold", Name: "投票一致阈值",
			Description: "多 LLM 投票一致性判断阈值（0-1）",
			ValueType:   "float", DefaultValue: "0.80", Min: strPtr("0.5"), Max: strPtr("1.0"), Step: strPtr("0.05")},
		{Group: "agent_llm", Key: "default_health_check_interval", Name: "健康检查间隔",
			Description: "LLM Provider 熔断器健康检查周期（秒）",
			ValueType:   "duration", DefaultValue: "30", Min: strPtr("5"), Max: strPtr("600"), Step: strPtr("5")},
		{Group: "agent_llm", Key: "default_circuit_open_duration", Name: "熔断器熔断时长",
			Description: "LLM Provider 熔断后保持 open 状态的时长（秒）",
			ValueType:   "duration", DefaultValue: "60", Min: strPtr("10"), Max: strPtr("3600"), Step: strPtr("10")},
		{Group: "agent_llm", Key: "default_health_check_timeout", Name: "健康检查超时",
			Description: "LLM Provider 健康检查请求的超时（秒）",
			ValueType:   "duration", DefaultValue: "5", Min: strPtr("1"), Max: strPtr("60"), Step: strPtr("1")},
		{Group: "agent_llm", Key: "default_failure_threshold", Name: "熔断失败阈值",
			Description: "LLM Provider 连续失败多少次后触发熔断",
			ValueType:   "int", DefaultValue: "5", Min: strPtr("1"), Max: strPtr("50"), Step: strPtr("1")},
		{Group: "agent_llm", Key: "default_http_timeout", Name: "默认 HTTP 超时",
			Description: "LLM 客户端 HTTP 请求默认超时（秒）",
			ValueType:   "duration", DefaultValue: "180", Min: strPtr("5"), Max: strPtr("600"), Step: strPtr("5")},
		{Group: "agent_llm", Key: "db_sink_stop_deadline", Name: "DB Sink 停止截止",
			Description: "Trace DB Sink 停止时等待的最大时间（秒）",
			ValueType:   "duration", DefaultValue: "3", Min: strPtr("1"), Max: strPtr("60"), Step: strPtr("1")},
		{Group: "agent_llm", Key: "default_semantic_threshold", Name: "语义缓存阈值",
			Description: "FAQ 语义缓存命中相似度阈值（0-1）",
			ValueType:   "float", DefaultValue: "0.95", Min: strPtr("0.5"), Max: strPtr("1.0"), Step: strPtr("0.05")},

		{Group: "knowledge", Key: "max_upload_file_size", Name: "知识库上传大小上限",
			Description: "知识库文档上传的最大文件大小（字节）",
			ValueType:   "int", DefaultValue: "52428800", Min: strPtr("1048576"), Max: strPtr("524288000"), Step: strPtr("1048576")},
		{Group: "knowledge", Key: "merchant_knowledge_max_len", Name: "商户知识库内容上限",
			Description: "外部知识库导入单条内容的最大字符数",
			ValueType:   "int", DefaultValue: "2000", Min: strPtr("100"), Max: strPtr("10000"), Step: strPtr("100")},

		{Group: "wechat", Key: "chat_ws_ping_period", Name: "微信 WS Ping 周期",
			Description: "微信渠道 WS 连接的心跳 ping 发送周期（秒）",
			ValueType:   "duration", DefaultValue: "30", Min: strPtr("5"), Max: strPtr("120"), Step: strPtr("1")},
		{Group: "wechat", Key: "chat_ws_pong_wait", Name: "微信 WS Pong 等待",
			Description: "微信渠道 WS 发送 ping 后等待 pong 的超时（秒）",
			ValueType:   "duration", DefaultValue: "60", Min: strPtr("10"), Max: strPtr("300"), Step: strPtr("1")},
		{Group: "wechat", Key: "chat_ws_write_wait", Name: "微信 WS 写等待",
			Description: "微信渠道 WS 单次写入的等待超时（秒）",
			ValueType:   "duration", DefaultValue: "10", Min: strPtr("1"), Max: strPtr("60"), Step: strPtr("1")},

		{Group: "inbox_sales", Key: "tg_lead_opportunity_threshold", Name: "Telegram 线索机会阈值",
			Description: "Telegram 线索识别判定为有机会的最低分数",
			ValueType:   "int", DefaultValue: "40", Min: strPtr("5"), Max: strPtr("200"), Step: strPtr("1")},
		{Group: "inbox_sales", Key: "unified_miner_lead_threshold", Name: "统一挖掘线索阈值",
			Description: "统一线索挖掘判定为有效线索的最低分数",
			ValueType:   "int", DefaultValue: "40", Min: strPtr("5"), Max: strPtr("200"), Step: strPtr("1")},
		{Group: "inbox_sales", Key: "preview_sample_limit", Name: "合并预览采样上限",
			Description: "OneID 合并预览的最大采样数",
			ValueType:   "int", DefaultValue: "20", Min: strPtr("1"), Max: strPtr("100"), Step: strPtr("1")},
		{Group: "inbox_sales", Key: "geo_lead_preview_max_len", Name: "Geo 线索洞察上限",
			Description: "Trace Learning 洞察返回的最大字符数",
			ValueType:   "int", DefaultValue: "200", Min: strPtr("10"), Max: strPtr("5000"), Step: strPtr("50")},

		{Group: "misc", Key: "deepl_timeout", Name: "DeepL 翻译超时",
			Description: "DeepL 翻译 API 请求超时（秒）",
			ValueType:   "duration", DefaultValue: "30", Min: strPtr("5"), Max: strPtr("300"), Step: strPtr("5")},
		{Group: "misc", Key: "reply_sem_timeout", Name: "回复语义超时",
			Description: "Webhook AI 回复语义分析超时（秒）",
			ValueType:   "duration", DefaultValue: "5", Min: strPtr("1"), Max: strPtr("60"), Step: strPtr("1")},
		{Group: "misc", Key: "ownership_cache_ttl", Name: "归属缓存 TTL",
			Description: "权限归属检查的结果缓存有效期（秒）",
			ValueType:   "duration", DefaultValue: "5", Min: strPtr("1"), Max: strPtr("300"), Step: strPtr("1")},
		{Group: "misc", Key: "summary_stale_threshold", Name: "Dashboard 摘要过期阈值",
			Description: "Dashboard SSE 摘要数据超过此时间视为过期需刷新（秒）",
			ValueType:   "duration", DefaultValue: "600", Min: strPtr("60"), Max: strPtr("3600"), Step: strPtr("30")},
		{Group: "misc", Key: "agentloop_history_max_candidates", Name: "AgentLoop 历史最大候选",
			Description: "AgentLoop 召回的历史对话最大候选数",
			ValueType:   "int", DefaultValue: "200", Min: strPtr("10"), Max: strPtr("10000"), Step: strPtr("10")},
	}
}
